### ISSUE TITLE
SQL Server Timeout on BulkInsert (Parallel execution)

### ISSUE THREAD

**Issue by jramirezdev** [MikaelEliasson/EntityFramework.Utilities#55]
I am working on a process to insert data from many flat files, my process uses TPL to insert simultaneously, I am getting various timeout exceptions randomly. My SQL Server version is 2005.

System.Data.SqlClient.SqlException (0x80131904): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection)   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning()   at System.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)   at System.Data.SqlClient.TdsParserStateObject.ReadSni(DbAsyncResult asyncResult, TdsParserStateObject stateObj)   at System.Data.SqlClient.TdsParserStateObject.ReadNetworkPacket()   at System.Data.SqlClient.TdsParserStateObject.ReadByte()   at System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternal()   at System.Data.SqlClient.SqlBulkCopy.WriteRowSourceToServer(Int32 columnCount)   at System.Data.SqlClient.SqlBulkCopy.WriteToServer(IDataReader reader)   at EntityFramework.Utilities.SqlQueryProvider.InsertItems[T](IEnumerable`1 items, String schema, String tableName, IList`1 properties, DbConnection storeConnection, Nullable`1 batchSize)   at EntityFramework.Utilities.EFBatchOperation`2.InsertAll[TEntity](IEnumerable`1 items, DbConnection connection, Nullable`1 batchSize)  at MyProject.FileProcessor.Process(List`1 parameters)

I have tried setting the CommandTimeout property from EF DataContext to 0, with no luck.

What is the default value the library is using for the BulkCopyTimeout property?

**Comment by MikaelEliasson** [comment]
Hi!

You can try to lower the batch size, See example here: https://github.com/MikaelEliasson/EntityFramework.Utilities/pull/20

I don't see any reason to run the inserts in parallell though. The narrow sector will be writing to disk for the database and that will not go faster if you run in parallell. Possibly even slower as it has to context switch. 

BulkCopyTimeout is using the default settings, so 30s.

**Comment by jramirezdev** [comment]
Hi Mikael,

I'm using TPL (concrete: Parallel.Foreach) to process many files at the same time, every file inserts its own data in different tables, so for example if there are 5 text files will also be 5 database tables. Inside the process of every file I'm splitting the content of the file in Chunks (based on the large of the file), to process every chunk I use a simple for loop get the portion of the file I need to process and then execute your library to insert chunks in every iteration. The timeout occurs per file processing, some files get processed ok and many others dont. 

I have tried following your example with no success, I continue getting the timeout and after 2 o 3 timeouts (files not processed) the SQL Server stops responding so it results in orphan processes.

Reading on the internet people says it could be solved increasing the value of the BulkCopyTimeout or just setting to 0 to wait infinitely, I would like to try that option but can not find a way to set it in your library. Could you help me with that?

**Comment by jramirezdev** [comment]
Just an update on this, I decided to test the timeout idea so I downloaded the source code from here, changed the value of BulkCopyTimeout to 0, and now I have no timeout exceptions.

It would be great if you add the possibility to set that value in your library, just as you did for the batchSize property.

I'm also facing another random issue, my text files could include duplicated records so sometimes I'm receiving an exception of duplicated key, I think that error is from Entity Framework because the destination table do not have any primary key or unique index defined.

System.ArgumentException: An item with the same key has already been added.   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)   at EntityFramework.Utilities.EFBatchOperation`2.InsertAll[TEntity](IEnumerable`1 items, DbConnection connection, Nullable`1 batchSize)

Mikael, any Idea about this?

**Comment by Bitfiddler** [comment]
I have this timeout issue as well.  I have set the CommandTimeout on my dbContext.Database.CommandTimeout to be 600 seconds but the InsertAll extension times out after 90 seconds (so it does not use this value).  We have one sql server with a lot of various services/apps running on it processing a lot of data at night so this is not unusual for commands to take a long time to execute.  Is the only way to override this to download the source?

**Comment by Iamcerba** [comment]
Hi, @MikaelEliasson,

Is it possible to make BulkCopyTimeout configurable?

**Comment by RudeySH** [comment]
@lamcerba There are currently one or two pull requests open that add this functionality. Unfortunately, it appears this project is dead and those pull requests never got merged.

[My fork](https://github.com/RudeySH/EntityFramework.Utilities) of this project is more up to date, and has added the posibility to configure the BulkCopyTimeout.

**Comment by Iamcerba** [comment]
@RudeySH,

Thank you for letting me know, appreciate.

**Comment by kosaurang** [comment]
Hello @RudeySH ,

How to configure BulkCopyTimeout. I don't see it on the new version : EFUtilities.1.0.2

**Comment by RudeySH** [comment]
@kosaurang My fork was never merged into this repository. It's not possible to configure `BulkCopyTimeout` and various other options if you use the the original EFUtilities 1.0.2 package. Try RudeySH.EFUtilities instead: https://www.nuget.org/packages/RudeySH.EFUtilities/
