### ISSUE TITLE
InsertAll: "Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by john-warpdevelopment** [MikaelEliasson/EntityFramework.Utilities#63]
I'm using EF 6 Code First, and when I try and insert into an object with optional One-To-One, or Many-To-One relationships I'm getting the error above.

e.g. the following model
```
Person{
    int PersonId;
    int AddressId;
    Address Address;
...
}```

Bulk inserts worked for the Address table which had a model such as:

```
Address{
    int AddressId;
    HashSet<Person> People;
...
}
```

**Comment by MikaelEliasson** [comment]
Hmm, might it be that the Address is null? Complex types most likely has to be initiated (like when you save with EF the normal way)

**Comment by john-warpdevelopment** [comment]
I did try instantiating the complex types, didn't help here is the complete model:

```
  public partial class Person : BaseEntity
    {
        #region Constructor
        public Person()
        {
            this.CreatedOnUtc = DateTime.Now;
            this.ModifiedOnUtc = DateTime.Now;
            this.Gender = Common.Gender.Male;
            this.PersonGuid = Guid.NewGuid();
            this.PersonStatus = PersonStatus.Enabled;
            this.Memberships = new HashSet<Member>();
            this.Leads = new HashSet<Lead>();
            this.LeadComments = new HashSet<LeadComment>();
            this.LeadAssigns = new HashSet<LeadAssign>();
            this.LeaveRequests = new HashSet<Leave>();
            this.LeaveApprovals = new HashSet<Leave>();
            this.Assets = new HashSet<Asset>();
            this.ContactDetails = new HashSet<ContactDetail>();
            this.Accounts = new HashSet<Account>();
            this.Documents = new HashSet<Document>();
        }
        #endregion

        #region Value Properties
        public Int32 PersonId { get; set; }
        public Nullable<int> AddressId { get; set; }

        public DateTime CreatedOnUtc { get; set; }
        public DateTime ModifiedOnUtc { get; set; }
        public Guid PersonGuid { get; set; }
        public String Title { get; set; }
        public String FirstName { get; set; }
        public String MiddleNames { get; set; }
        public String Surname { get; set; }
        public String Alias { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }

        public String Email { get; set; }
        internal string GenderEnum { get; set; }
        internal string PersonStatusEnum { get; set; }
        public String PasswordSalt { get; set; }
        public String Password { get; set; }
        public String Tag { get; set; }
        public string IdNumber { get; set; }
        public string AccountNumber { get; set; }

        #endregion

        #region Enumeration Properties
        public Gender Gender
        {
            get { return (Gender)Enum.Parse(typeof(Gender), this.GenderEnum); }
            set { this.GenderEnum = value.ToString(); }
        }

        public PersonStatus PersonStatus
        {
            get { return (PersonStatus)Enum.Parse(typeof(PersonStatus), this.PersonStatusEnum); }
            set { this.PersonStatusEnum = value.ToString(); }
        }
        #endregion

        #region Navigation Properties

		public ICollection<Member> Memberships { get; set; }

        public ICollection<Lead> Leads { get; set; }

        public ICollection<LeadComment> LeadComments { get; set; }

        public ICollection<LeadAssign> LeadAssigns { get; set; }

        public Address Address { get; set; }

        public ICollection<Leave> LeaveApprovals { get; set; }

        public ICollection<Leave> LeaveRequests { get; set; }

        public ICollection<Asset> Assets { get; set; }

        public PersonLeaveInfo PersonLeaveInfo { get; set; }

        public ICollection<ContactDetail> ContactDetails { get; set; }

        public ICollection<Account> Accounts { get; set; }
        
       
        public ICollection<Document> Documents { get; set; }
        #endregion
    }
```

what's weird is it worked for some of my other entities that have complex types , and enumerations same as this one.

**Comment by MikaelEliasson** [comment]
I might need to debug this one. Did the types it work for have the same base class?

If they did I suspect the internal properties but I'll have to try it.

**Comment by john-warpdevelopment** [comment]
Yes , that base class is empty it's just used for generics.

**Comment by catinodeh** [comment]
I had the same problem. My object has only primitive properties (date, string and int) and my table accepts NULL on all of them. Any clue what could be causing this ?

This is my exception:

2016-06-03 12:13:12,633 [8] ERROR [Controllers.LogsController+<Save>d__1.MoveNext] System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at EntityFramework.Utilities.EfMappingFactory.GetMappingsForContext(DbContext context)
   at EntityFramework.Utilities.EFBatchOperation`2.InsertAll[TEntity](IEnumerable`1 items, DbConnection connection, Nullable`1 batchSize)
   at WRE.George.API.Controllers.LogsController.<Save>d__1.MoveNext() in D:\TFS Projects\WRE.George\WRE.George.API\Controllers\LogsController.cs:line 59
