### ISSUE TITLE
Conversion from string " " to type 'Double' Error

### ISSUE THREAD

**Issue by a6datta** [MikaelEliasson/EntityFramework.Utilities#64]
Hi I am trying to update 4 columns. The data types are string. I am getting this error. I am using EF 6.1.3. First i tried with all columns now with one but no luck.

 System.InvalidCastException: Conversion from string " " to type 'Double' is not valid. ---> System.FormatException: Input string was not in a correct format.
   at Microsoft.VisualBasic.CompilerServices.Conversions.ParseDouble(String Value, NumberFormatInfo NumberFormat)
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToDouble(String Value, NumberFormatInfo NumberFormat)
   --- End of inner exception stack trace ---
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToDouble(String Value, NumberFormatInfo NumberFormat)

My code
EFBatchOperation.[For](poentities, poentities.LondonA).UpdateAll(list, Function(x) x.ColumnsToUpdate(Function(c) c.FullA))

**Comment by wind-raven** [comment]
With out the entity code and the schema there is not much we could do to track down the error since its an issue converting a string with a single space to a Double.

If you can provide additional detail it may help tracking things down.
